# Generated by Django 4.1.5 on 2023-01-24 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento', '0002_alter_departamento_options_alter_departamento_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('surnames', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('job', models.CharField(choices=[('0', 'INFORMATICO'), ('1', 'ADMINISTRADOR'), ('2', 'ECONOMISTA'), ('3', 'GEOLOGO')], max_length=50, verbose_name='Trabajo')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamento.departamento')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Empleados',
                'ordering': ['first_name'],
                'unique_together': {('first_name', 'surnames')},
            },
        ),
    ]
