# Generated by Django 4.1.5 on 2023-01-24 11:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_persona_habilidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='hoja_vida',
            field=ckeditor.fields.RichTextField(default='texto'),
            preserve_default=False,
        ),
    ]
