# Generated by Django 4.1.5 on 2023-01-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_alter_persona_surnames'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='surnames',
            field=models.CharField(max_length=50, verbose_name='Apellidos'),
        ),
    ]
